# Generated by Django 5.0.6 on 2024-12-05 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_list', '0002_orderdetail_delete_orderdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='date',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='payment_amount',
        ),
    ]
