# Generated by Django 5.0.6 on 2024-12-05 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_list', '0002_orderdetail_delete_orderdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='menu_item',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='menu_items',
            field=models.ManyToManyField(related_name='order_details', to='sales_list.menuitem'),
        ),
    ]
