# Generated by Django 5.0.6 on 2024-12-05 04:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_list', '0003_ordersummary_remove_orderdetail_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='order_summary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales_list.ordersummary'),
        ),
        migrations.AddField(
            model_name='ordersummary',
            name='complete',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='menu_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales_list.menuitem'),
        ),
        migrations.AlterField(
            model_name='ordersummary',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
