# Generated by Django 5.0.6 on 2024-12-05 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_list', '0004_orderdetail_order_summary_ordersummary_complete_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordersummary',
            name='complete',
        ),
    ]
