# Generated by Django 5.0.6 on 2024-12-05 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_list', '0005_remove_ordersummary_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='menu_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sales_list.menuitem'),
        ),
    ]
